# Generated by Django 5.0 on 2023-12-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolyo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projelerim',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='projelerim',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
