# Generated by Django 5.0 on 2023-12-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolyo', '0002_alter_projelerim_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projelerim',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
