# Generated by Django 4.2.3 on 2023-12-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
