# Generated by Django 4.2.3 on 2023-12-22 16:16

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_houses_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='profile_pic')),
                ('description', models.TextField()),
                ('position', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=50), unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='houses',
            options={'verbose_name': 'Ev', 'verbose_name_plural': 'Evler'},
        ),
        migrations.AlterField(
            model_name='houses',
            name='description',
            field=models.TextField(verbose_name='Evin acıklaması'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='image',
            field=models.ImageField(upload_to='houses', verbose_name='Evin resmi:'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Satışta mı:'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Evin adı:'),
        ),
        migrations.AddField(
            model_name='houses',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.profile'),
        ),
    ]
