# Generated by Django 5.0 on 2023-12-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_houses_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
